DROP TABLE IF EXISTS TB_HEROIS;
CREATE TABLE TB_HEROIS (
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NOME TEXT NOT NULL,
  PODER TEXT NOT NULL
);

INSERT INTO TB_HEROIS (NOME, PODER) VALUES
('Flash', 'Velocidade'),
('Aquaman', 'Falar com os animais'),
('Batman', 'Dinheiro');

SELECT * FROM TB_HEROIS;
SELECT * FROM TB_HEROIS WHERE NOME = 'Flash';
SELECT NOME FROM TB_HEROIS WHERE NOME = 'Flash';

UPDATE TABLE TB_HEROIS SET NOME = "Goku", PODER = "Deus"
WHERE ID = 1;

DELETE FROM TB_HEROIS where ID = 2;